issuecreator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('issues.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

issues/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views as views

urlpatterns = [
    path('', views.index, name='index'),
    path('newspaper/', views.newspaper, name='newspaper'),
	path('result/', views.searchissue, name='searchissue'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('issue/<int:pk>/', views.IssueDetailView.as_view(), name='issue-detail'),
    path('issue/new/', views.IssueCreateView.as_view(), name='issue-create'),
    path('issue/<int:pk>/update/', views.IssueUpdateView.as_view(), name='issue-update'),
    path('issue/<int:pk>/delete/', views.IssueDeleteView.as_view(), name='issue-delete'),
    path('user/<str:username>/', views.UserListView.as_view(), name='user-issues'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('profile/', views.view_profile, name='view_profile'),
    path('requirement/<int:comment_id>/<str:opition>/', views.UpdateCommentVote.as_view(), name='requirement_comment_vote'),
    path('irequirement/<int:issue_id>/<str:opition>/', views.UpdateIssueVote.as_view(), name='requirement_issue_vote'),
]

issues/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, Comment
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2',
                  )

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

templates/add_comment_to_post.html
{% extends 'header.html' %}

{% block content %}
{{ form.errors}}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.comment }}
        <button type="submit" class="save btn btn-default">ADD</button>
    </form>
{% endblock %}

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <title>
        {% block title %}{% endblock %}
    </title>
</head>

<body>
<!--here small change-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item"><a class="nav-link" href="{% url 'newspaper' %}">Newspaper</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'issue-create' %}">New Issue</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'view_profile' %}">Profile</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <form class="d-flex" action="{% url 'searchissue' %}" method="GET" value="{{request.GET.q}}">
                <input class="form-control mr-sm-2" type="text" name="q" value="{{request.GET.q}}" placeholder="Search..." aria-label="Search">
               <button class="btn btn-outline-info my-2 my-sm-0" name="submit" type="submit" value="Search">Search</button>
            </form>
              

            {% else %}
             <div class="d-flex">
              <a class="btn btn-success" href="{% url 'register' %}">Register</a>&nbsp;&nbsp;&nbsp;
              <a class="btn btn-success" href="{% url 'login' %}">Login</a>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
    </nav>

    <main role="main" >
                {% if messages %} {% for message in messages %}

                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %} {% endif %} {% block content %}{% endblock %}
    </main>
    <br>
    <!--here small change-->
    <div id="sticky-footer" class="py-4 bg-secondry text-black-50">
        <div class="container text-center">
            <small>Copyright &copy; Swaroop</small>
        </div>
    </div>

</body>


</html>

templates/index.html
{% extends "header.html"%}
{% block title %}Issue Creator{% endblock %}
{% block content %}


</br>
{% for issue in issues %}

<div class="card shadow p-3 mb-5 bg-white rounded">
	<div style="text-align: inline;">
		<img src="{{ issue.user.userprofile.thumbnail.url }}" width="40" height="40" alt="Profile Image" style="border-radius: 50%;">
		&nbsp;
		<a class="card-subtitle mb-2 text-muted" href="{% url 'user-issues' issue.user.username %}">{{ issue.user }}</a>
	</div>

	<div class="card-body">
		<a class="card-title" style="font-size: 2em;" href="{% url 'issue-detail' issue.id %}">{{ issue.title }}</a>
		</br>
		<small>{{ issue.date_issueed|date:"F d, Y" }}</small>
		</br></br>
		<p class="card-text">{{ issue.description|truncatewords:"30" }}</p>

	</div>
	<a href="{% url 'issue-detail' issue.id %}">Comments: {{ issue.comments.count }}</a>
	<div >
		{% if user in issue.likes.users.all%}
		<!-- already liked-->
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='like' %}> 
		<i class='fas fa-thumbs-up'></i> <span>{{issue.get_total_likes}}</span>
		</a>
		{% else %}
		<!--not liked-->
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='like' %}>
			<i class='far fa-thumbs-up'></i>
		<span>{% if issue.get_total_likes  %}{{issue.get_total_likes}} {% else %} 0
		{% endif %}</span>
		</a>
		{% endif %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		{% if request.user in issue.dis_likes.users.all %}
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='dis_like' %}>
			<i class="fas fa-thumbs-down">
		<span>{{issue.get_total_dis_likes}}</span></i>
		</a>
		{% else %}
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='dis_like' %}>
			<i class="far fa-thumbs-down">
		<span>{% if  issue.get_total_dis_likes %}{{issue.get_total_dis_likes}}
		{% else %} 0 {% endif %}</span></i>
		</a>
		{% endif %}
	</div>
</div>

{% endfor %}

{% if issues.paginator.num_pages > 1 %}

<!-- start -->
{% include 'issue/_pagination.html' with issues=issues %}
<!-- end -->

{% endif %}


</div>

{% endblock content %}

templates/login.html
{% extends "header.html" %} 
{% block title %}Login{% endblock %} 
{% block content %} 
    {% load widget_tweaks %}
        <div class="container">
            <div class="row">
                <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                    <div class="card card-signin my-5">
                        <!--Here-->
                        <div class="card-body bg-dark text-white">
                            <!--Here-->
                            <h5 class="card-title text-center">SIGN IN</h5>
                            <form class="form-signin" method="POST">
                                {% csrf_token %} {% for error in form.non_field_errors %}
                                <strong style="color: red">{{ error }}</strong> {% endfor %}
                                <br>
                                <!--Here-->
                                <div class="form-label-group">
                                    <label for="id_username">User name</label>
                                    {% render_field form.username placeholder=form.username.label class+="form-control" %}
                                    <br>
                                </div>
                                <!--Here-->
                                <div class="form-label-group">
                                    <label for="id_password">Password</label>
                                    {% render_field form.password placeholder=form.password.label class+="form-control" %}
                                    <br>
                                </div>
                                <!--Here-->
                                <button class="btn rounded-pill btn-md btn-info btn-block text-capitalize" type="submit">Sign in</button>
                               
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<style>
    body
    {
        background-color: grey;
    }


</style>

{% endblock %}

templates/logout.html
{% extends "header.html" %}
{% block title %}Logout{% endblock %} 
{% block content %}
<center>
    <br><br><br><br>
<h2>You have been logged out</h2>
<br><br>
<div class="border-top pt-3">
    <small class="text-muted">
        <!--here-->
        <a class="btn btn-primary btn-md" href="{% url 'login' %}">Log In Again</a>
    </small>
</div>
</center>
{% endblock content %}

templates/newissue.html
<form id="post_form" method="post" action="" enctype="multipart/form-data">

    {% csrf_token %}
    {% for hidden in postForm.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in postForm %}
        {{ field }} <br />
    {% endfor %}

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}


    <input type="submit" name="submit" value="Submit" />
</form>

templates/newspaper.html
{% extends "header.html"%}
{% block title %}Issue Creator{% endblock %}
{% block content %}

<h3>Newspapers</h3>
</br>
{% for issue in issues %}

<div class="card shadow p-3 mb-5 bg-white rounded">
	<div style="text-align: inline;">
		<img src="{{ issue.user.userprofile.thumbnail.url }}" width="40" height="40" alt="Profile Image" style="border-radius: 50%;">
		&nbsp;
		<a class="card-subtitle mb-2 text-muted" href="{% url 'user-issues' issue.user.username %}">{{ issue.user }}</a>
	</div>

	<div class="card-body">
		<a class="card-title" style="font-size: 2em;" href="{% url 'issue-detail' issue.id %}">{{ issue.title }}</a>
		</br>
		<small>{{ issue.date_issueed|date:"F d, Y" }}</small>
		</br></br>
		<p class="card-text">{{ issue.description|truncatewords:"30" }}</p>

	</div>
	<a href="{% url 'issue-detail' issue.id %}">Comments: {{ issue.comments.count }}</a>
	<div >
		{% if user in issue.likes.users.all%}
		<!-- already liked-->
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='like' %}> 
		<i class='fas fa-thumbs-up'></i> <span>{{issue.get_total_likes}}</span>
		</a>
		{% else %}
		<!--not liked-->
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='like' %}>
			<i class='far fa-thumbs-up'></i>
		<span>{% if issue.get_total_likes  %}{{issue.get_total_likes}} {% else %} 0
		{% endif %}</span>
		</a>
		{% endif %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		{% if request.user in issue.dis_likes.users.all %}
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='dis_like' %}>
			<i class="fas fa-thumbs-down">
		<span>{{issue.get_total_dis_likes}}</span></i>
		</a>
		{% else %}
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='dis_like' %}>
			<i class="far fa-thumbs-down">
		<span>{% if  issue.get_total_dis_likes %}{{issue.get_total_dis_likes}}
		{% else %} 0 {% endif %}</span></i>
		</a>
		{% endif %}
	</div>
</div>
{% empty %}
    <p>No Newspapers here :(</p>

{% endfor %}

{% if issues.paginator.num_pages > 1 %}

<!-- start -->
{% include 'issue/_pagination.html' with issues=issues %}
<!-- end -->

{% endif %}


</div>

{% endblock content %}

templates/profile.html
{% extends "header.html" %} 
{% block title %}Profile{% endblock %} {% block content %}
<br>
<div class="card shadow  portfolio container">
    <div align="center">
        <img src="{{ user.userprofile.image.url }}" width="240"> 
    </div>
    <div>
        <h1>Profile</h1>
        <p>Username: {{ user }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
    </div>
</div>



{% endblock %}

templates/register.html
{% extends "header.html"%}
{% block title %}Register{% endblock %}

{% block content %}
{% load widget_tweaks %}

<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <!--here-->
                <div  class="card bg-dark text-white text-capitalize card-signin my-5">
                    <div class="card-body">
                        <!--here-->
                        <h5 class="card-title text-center"><b>REGISTER</b></h5>
                        {{ form.errors}}
                             {{ form.help_text }}
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                             <div class="form-label-group">
                             
                                {% render_field form.username placeholder=form.username.label class+="form-control"  %}
                                <label for="id_username">Username</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.email placeholder=form.email.label class+="form-control"  %}
                                <label for="id_email">Email</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.first_name placeholder=form.first_name.label class+="form-control"  %}
                                <label for="id_first_name">First Name</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.last_name placeholder=form.last_name.label class+="form-control"  %}
                                <label for="id_last_name">Last Name</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.password1 placeholder=form.password1.label class+="form-control"  %}
                                <label for="id_password1">Password</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.password2 placeholder=form.password2.label class+="form-control"  %}
                                <label for="id_password2">Confirm Password</label>
                            </div>
                            <!--here-->
                            <button class="btn btn-sm btn-info text-capitalize"
                                type="submit">Register</button>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>







<style>
    :root {
        --input-padding-x: 1.5rem;
        --input-padding-y: .75rem;
    }

    body {

    /********************here****************/
        background: grey;  /* fallback for old browsers */
/*background: -webkit-linear-gradient(to right, #2F80ED, #56CCF2);  /* Chrome 10-25, Safari 5.1-6 */
/*background: linear-gradient(to right, #2F80ED, #56CCF2); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */


        
        background-size: cover;
        background-position: center;
    }

    .card-signin {
        border: 0;
        /*here*/
        box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
    }

    .card-signin .card-title {
        margin-bottom: 2rem;
        font-weight: 300;
        font-size: 1.5rem;
    }

    .card-signin .card-body {
        padding: 2rem;
    }

    .form-signin {
        width: 100%;
    }

    .form-signin .btn {
        font-size: 80%;
        border-radius: 5rem;
        letter-spacing: .1rem;
        font-weight: bold;
        padding: 1rem;
        transition: all 0.2s;
    }

    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }

    .form-label-group input {
        height: auto;
        border-radius: 2rem;
    }

    .form-label-group>input,
    .form-label-group>label {
        padding: var(--input-padding-y) var(--input-padding-x);
    }

    .form-label-group>label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0;
        /* Override default `<label>` margin */
        line-height: 1.5;
        color: #495057;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
    }

    .form-label-group input::-webkit-input-placeholder {
        color: transparent;
    }

    .form-label-group input:-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-moz-placeholder {
        color: transparent;
    }

    .form-label-group input::placeholder {
        color: transparent;
    }

    .form-label-group input:not(:placeholder-shown) {
        padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
        padding-bottom: calc(var(--input-padding-y) / 3);
    }

    .form-label-group input:not(:placeholder-shown)~label {
        padding-top: calc(var(--input-padding-y) / 3);
        padding-bottom: calc(var(--input-padding-y) / 3);
        font-size: 12px;
        color: #777;
    }

    .btn-google {
        color: white;
        background-color: #ea4335;
    }

    .btn-facebook {
        color: white;
        background-color: #3b5998;
    }

    /* Fallback for Edge
-------------------------------------------------- */

    @supports (-ms-ime-align: auto) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input::-ms-input-placeholder {
            color: #777;
        }
    }

    /* Fallback for IE
-------------------------------------------------- */

    @media all and (-ms-high-contrast: none),
    (-ms-high-contrast: active) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input:-ms-input-placeholder {
            color: #777;
        }
    }
</style>
{% endblock content %}

templates/search.html
{% extends "header.html"%}

{% block content %}

<h1> Search </h1>
{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
{% block title %}Search result for {{ request.GET.q }}{% endblock %}
<h3>Results for <b>{{ request.GET.q }}</b></h3>
<br /><br />

{% for issue in results %}


<div class="card shadow p-3 mb-5 bg-white rounded">
	<div style="text-align: inline;">
		<img src="{{ issue.user.userprofile.thumbnail.url }}" width="40" height="40" alt="Profile Image" style="border-radius: 50%;">
		&nbsp;
		<a class="card-subtitle mb-2 text-muted" href="{% url 'user-issues' issue.user.username %}">{{ issue.user }}</a>
	</div>

	<div class="card-body">
		<a class="card-title" style="font-size: 2em;" href="{% url 'issue-detail' issue.id %}">{{ issue.title }}</a>
		</br>
		<small>{{ issue.date_issueed|date:"F d, Y" }}</small>
		</br></br>
		<p class="card-text">{{ issue.description|truncatewords:"30" }}</p>

	</div>
	<a href="{% url 'issue-detail' issue.id %}">Comments: {{ issue.comments.count }}</a>
	<div >
		{% if user in issue.likes.users.all%}
		<!-- already liked-->
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='like' %}> 
		<i class='fas fa-thumbs-up'></i> <span>{{issue.get_total_likes}}</span>
		</a>
		{% else %}
		<!--not liked-->
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='like' %}>
			<i class='far fa-thumbs-up'></i>
		<span>{% if issue.get_total_likes  %}{{issue.get_total_likes}} {% else %} 0
		{% endif %}</span>
		</a>
		{% endif %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		{% if request.user in issue.dis_likes.users.all %}
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='dis_like' %}>
			<i class="fas fa-thumbs-down">
		<span>{{issue.get_total_dis_likes}}</span></i>
		</a>
		{% else %}
		<a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='dis_like' %}>
			<i class="far fa-thumbs-down">
		<span>{% if  issue.get_total_dis_likes %}{{issue.get_total_dis_likes}}
		{% else %} 0 {% endif %}</span></i>
		</a>
		{% endif %}
	</div>
</div>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

</br>


{% endblock content %}

templates/user_posts.html
{% extends "header.html"%}

{% block title %}User Details{% endblock %}

{% block content %} 


{% for issue in issues|slice:":1" %}

</br>
<div class="card shadow  portfolio">
    <div class="bio-image">
        <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><img src="{{ issue.user.userprofile.image.url }}" alt="image" width="200" height="200"  /></a>
        <h1>{{ issue.user.first_name }} {{ issue.user.last_name }}</h1
    </div>
    <div >
                    <p>Name : {{ issue.user.first_name }} {{ issue.user.last_name }}</p>
                        <br>
               
    </div>


{% endfor %}

<h1 align="left">Posts</h1>
 {% for issue in issues %}

<div class="card shadow p-3 mb-5 bg-white rounded">
    <div style="text-align: inline;">
        <img src="{{ issue.user.userprofile.image.url }}" width="20" height="20" alt=""> &nbsp;
        <a class="card-subtitle mb-2 text-muted" href="{% url 'user-issues' issue.user.username %}">{{ issue.user }}</a>
</div>

<div class="card-body">
    <a class="card-title" style="font-size: 2em;" href="{% url 'issue-detail' issue.id %}">{{ issue.title }}</a>
    </br>
    <small>{{ issue.date_issueed|date:"F d, Y" }}</small>
    </br>
    </br>
    <p class="card-text">{{ issue.description|truncatewords:"30" }}</p>

</div>
<a href="{% url 'issue-detail' issue.id %}">Comments: {{ issue.comments.count }}</a>


<div >
    {% if user in issue.likes.users.all%}
    <!-- already liked-->
    <a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='like' %}> 
    <i class='fas fa-thumbs-up'></i> <span>{{issue.get_total_likes}}</span>
    </a>
    {% else %}
    <!--not liked-->
    <a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='like' %}>
        <i class='far fa-thumbs-up'></i>
    <span>{% if issue.get_total_likes  %}{{issue.get_total_likes}} {% else %} 0
    {% endif %}</span>
    </a>
    {% endif %}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    {% if request.user in issue.dis_likes.users.all %}
    <a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='dis_like' %}>
        <i class="fas fa-thumbs-down">
    <span>{{issue.get_total_dis_likes}}</span></i>
    </a>
    {% else %}
    <a href={% url 'requirement_issue_vote' issue_id=issue.pk opition='dis_like' %}>
        <i class="far fa-thumbs-down">
    <span>{% if  issue.get_total_dis_likes %}{{issue.get_total_dis_likes}}
    {% else %} 0 {% endif %}</span></i>
    </a>
    {% endif %}
</div>


</div>

{% endfor %}
</div>

{% if issues.paginator.num_pages > 1 %}

<!-- start -->
{% include 'issue/_pagination.html' with issues=issues %}
<!-- end -->

{% endif %}

<style>
    .portfolio {
        padding: 6%;
        text-align: center;
    }
    
    .bio-image img {
        border-radius: 50%;
    }
</style>

{% endblock content %}